### ISSUE TITLE
trouble to ssh into my vagrant machine

### ISSUE THREAD

**Issue by dulhaver** [coderbunker/linux#1]
It's my first time using vagrant, so I have some trouble. Maybe someome here can help

Got my ubn1404 running (W7 host) apparently.

I go inside the directory of the vagrant box I want to use and say
`vagrant up`
and then
`vagrant ssh`

This returns an IP address, a username, an ssh port (2222) and location of the private key on my host machine (`E:/Vagrant/trusty64/.vagrant/machines/default/virtualbox/private_key`)
but the folder is empty ... any ideas what I can do?

**Comment by sylvainv** [comment]
`E:/Vagrant/trusty64/.vagrant/machines/default/virtualbox/private_key` shouldn't be a folder but a file. Do you mean the file is empty ? Or `virtualbox` folder is empty ?

**Comment by albertogalan** [comment]
Try to install a different machine other than ubuntu , and see what happens, if you have the same error.

**Comment by dulhaver** [comment]
@sylvainv true ... it's a file. Still I can't connect apparently because there is nothing below that IP 172.0.0.1 (neither can can ping it). Total vagrent newb ... how can I check which machine is running? `vagrant box list` does something else I believe

**Comment by dulhaver** [comment]
just noted that what I belive to be the IP addresse is called `hostname` (still it looks like an IP address 172.2.2.1) Can it be that this is part of my problem?

(found that out by saying `vagrant ssh-config`, if anybody is interested)

ssh to my hosts IP address with port 2222 doesn't work either though (connection refused)
`vagrant status` (like all the other commands sent while being inside of the machines folder) says it was `running (virtualbox)`. So it seems to live at least

**Comment by sylvainv** [comment]
But `vagrant ssh` should take you on the machine, not return you the port and address, can you take screenshots ?

```
vagrant up
vagrant ssh
```

**Comment by dulhaver** [comment]
well ...  Our internal network is `172.xx.xx.xx` and so I misread the vagrant `127.x.x.x` as `172.x.x.x`  

closing this issue gracefully herewith, sorry guys for the false alarm. At least we have established using the issues
