### ISSUE TITLE
Copy 'n' paste content from the Online Course Content

### ISSUE THREAD

**Issue by dulhaver** [coderbunker/linux#3]
... seems to be restricted. Has anybody by chance found a hack to do this (which would be very helpful to make notes or whatever)?

**Comment by vrms** [comment]
here is one workaround that works for firefox

1. mark text
2. ctrl + c
3. ctrl + f
4. ctrl + x
5. ctrl + v (in your external doc)

**Comment by dulhaver** [comment]
here is one method that works for firefox
1. mark text
2. ctrl + c
3. ctrl + f
4. ctrl + x
5. ctrl + v (in your external doc)
