### ISSUE TITLE
online content on mobile device ...

### ISSUE THREAD

**Issue by dulhaver** [coderbunker/linux#4]
... seems not to work in standard browser (ff on android in my case). Is there an app or any other way?

**Comment by sylvainv** [comment]
Not work is too vague of a description to be able to help you.

**Comment by dulhaver** [comment]
ok, true. here is what I expect
1. log in to https://training.linuxfoundation.org using firefox on android
2. open >> My Portal
3. see the "LFS201 Essentials of System Administration" listed and be able to follow the link to it (and access the content then)

what actually happens is that after step **2.)** there is nothing listed. I can see a dropdown menu on the top right, which lists existing classes if you chose "training" but does not offer 'Launch Course' as it does in a 'regular' browser.

To me that smells as if the site is just not ready for a mobile browser. So let's say there was an app of the Linux foundation or respectively the online Training platform they use I'd assume is to work well with such.

Can you access the Course via mobile device?

**Comment by dulhaver** [comment]
according http://support.360training.com/support/home support staff they are just not ready for mobile access but expect to be so starting with Jan 2017
